<a href="https://colab.research.google.com/github/CamronEdwards2021/Stats-notes/blob/main/Edwards_Stats_notes_lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import imageio
from PIL import Image

In [ ]:
for i in range(1,4):
  print(i) 

1
2
3


In [ ]:
for i in range(1):
  print("test number", i)

test number 0


In [ ]:
def square(x):
  return x**2 #defines the term square to square whatever is inserted into it

In [ ]:
square(5)

25

In [ ]:
square(square(square(2))) #example of using multiple square commands into each other

256

In [ ]:
def add_two(x):
  return x+2 #creates an add two command that will add 2 to whatever is input

In [ ]:
add_two(5)

7

In [ ]:
choice = "apple" #defines the command choice

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.") #gives a command if you choose "apple"

You choose apples.


In [ ]:
choice = "orange"

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
if choice == "apple":

    print("You choose apples.")
    print("thank you come agian")

elif choice == "orange":

    print("You choose oranges.")
    print("thank you come again")

else:
    
    print("You did not choose apples or oranges.") #adds a command if oranges are chosen 

You choose oranges.
thank you come again


In [ ]:
choice = input("please enter your choice(i.e. apple):") #gives a prompt for your choice

please enter your choice(i.e. apple):orange


In [ ]:
choice 

'orange'

In [ ]:
np.random.permutation(52) #prints 52 numbers in a random order

array([21, 43, 27, 15, 29,  7, 30,  9, 46, 38, 14,  4, 13, 34, 11, 50, 22,
       26,  8, 40,  2, 10, 42, 28, 16, 20, 39,  6, 44, 37, 41, 24, 25, 18,
       49, 32, 33, 36, 48, 23,  0, 19, 45, 31, 47,  1, 17, 12, 35,  3,  5,
       51])

In [ ]:
cards=np.random.permutation(52) #defines the term cards

In [ ]:
cards #example of the cards command

array([44, 14, 28, 36, 24, 25, 47, 23, 43,  3, 39, 12, 49, 40, 41,  7, 48,
       10,  8, 19, 32, 26,  0, 29, 46,  1, 27, 30, 51, 45, 22,  5, 34,  2,
       16,  9, 17, 33, 11,  4, 13, 20, 38, 21, 18,  6, 50, 35, 37, 31, 42,
       15])

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #defines the names for the cards

In [ ]:
suits #list of suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [ ]:
names #list of names

['Ace',
 'Two',
 'Three',
 'Four',
 'Five',
 'Six',
 'Seven',
 'Eight',
 'Nine',
 'Ten',
 'Jack',
 'Queen',
 'King']

In [ ]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit] #defines the term card name to return a name and suit

In [ ]:
card_name(0) #first card in the deck

'Ace of Clubs'

In [ ]:
card_name(51) #last card in the deck

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52) #gives the word cards the np.random.permutation command

In [ ]:
cards

array([43,  3, 40, 25, 32, 10, 23, 33, 13, 47, 19, 30,  1, 44, 49, 11, 24,
       46, 36, 42, 45, 16,  4, 12, 38, 51,  7, 50, 35, 31, 37,  0, 18, 22,
       21, 15, 14, 20,  8, 17,  5, 26, 29, 41,  2, 48, 28,  6, 27,  9, 34,
       39])

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png" #gives the cards and image 

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13) 

In [ ]:
suit[i]

'k'

In [ ]:
card[j]

'k'

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) 

In [ ]:
from IPython.core.display import display, HTML #imports core display and display HTML

In [ ]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [ ]:
show_img(img) #shows image

In [1]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

NameError: ignored